<a href="https://colab.research.google.com/drive/1D1FSinokFoygB5UxCOQGiYNtGVv_Rbh6?usp=sharing">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

This tutorial needs data so if you working on colab follow the below data setup instruction

# Data Setup Instructions

These are the instructions for mounting the data from google drive to colab and accessing it in the colab.

STEP 1 - After opening the tutorial in  your colab, go to folder button and click on mount google drive

STEP 2 - drive folder will be mounted in the current directory of /content, you can access it as below

In [ ]:
# print current directory
%pwd

'/content'

In [ ]:
%ls

drive/  sample_data/

STEP 3 - Find your data folder where you saved the data and sym link it to /content folder so as to simplify data access

In the current case the Data folder is located at this path in google drive (Use your own data path in your case)

/content/drive/Othercomputers/My MacBook Pro/Data/

We can sym link it to /content folder using the following command

In [ ]:
# sym linked the original data folder to new location at /content/Data
!ln -s "/content/drive/Othercomputers/My MacBook Pro/Data" "/content/Data"

Now we can access the data from this folder by simply giving the file path name after /Data

# Dataset Introduction

Let us explore IMDB dataset hosted on kaggle - https://www.kaggle.com/stefanoleone992/imdb-extensive-dataset

So, There are 4 csv files hosted on kaggle for IMDB dataset

**1. title dataset**<br>
The title principals dataset includes 835,513 cast members roles in movies with attributes such as IMDb title id, IMDb name id, order of importance in the movie, role, and characters played.

**2.names dataset**<br>
The names dataset includes 297,705 cast members with personal attributes such as birth details, death details, height, spouses, children, etc.

**3. movies dataset**<br>
The movies dataset includes 85,855 movies with attributes such as movie description, average rating, number of votes, genre, etc.

**4. ratings dataset**<br>
The ratings dataset includes 85,855 rating details from demographic perspective.

For now we will just be exploring one data set so as to simplify our learning of Pandas

We will be exploring movies dataset

movies dataset has been downloaded from kaggle and saved in following folder

Data/IMDB_rotten_tomato_dataset/IMDB/IMDb movies.csv

# Data loading - csv files

In [ ]:
# Import pandas library
import pandas as pd

In [ ]:
# if you are working with this tutorial on local machine use the file path where the data is saved in your computer
movies = pd.read_csv("Data/IMDB_rotten_tomato_dataset/IMDB/IMDb movies.csv")
# We can use .head command to quickly observe the first 5 rows of the dataset
movies.head()

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (3) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

  imdb_title_id  ... reviews_from_critics
0     tt0000009  ...                  2.0
1     tt0000574  ...                  7.0
2     tt0001892  ...                  2.0
3     tt0002101  ...                  3.0
4     tt0002130  ...                 14.0

[5 rows x 22 columns]

In [ ]:
# for seeing the first 10 rows we can use the .head(10)
movies.head(10)

  imdb_title_id  ... reviews_from_critics
0     tt0000009  ...                  2.0
1     tt0000574  ...                  7.0
2     tt0001892  ...                  2.0
3     tt0002101  ...                  3.0
4     tt0002130  ...                 14.0
5     tt0002199  ...                  5.0
6     tt0002423  ...                  9.0
7     tt0002445  ...                  5.0
8     tt0002452  ...                  1.0
9     tt0002461  ...                  1.0

[10 rows x 22 columns]