<a href="https://colab.research.google.com/drive/1Q_N2LlwyDv7fzumyAViA4y2_jRsgMq65?usp=sharing">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

This tutorial needs data so if you working on colab follow the below data setup instruction

# Data Setup Instructions

These are the instructions for mounting the data from google drive to colab and accessing it in the colab.

STEP 1 - After opening the tutorial in  your colab, go to folder button and click on mount google drive

STEP 2 - drive folder will be mounted in the current directory of /content, you can access it as below

In [ ]:
# print current directory
%pwd

'/content'

In [ ]:
%ls

drive/  sample_data/

STEP 3 - Find your data folder where you saved the data and sym link it to /content folder so as to simplify data access

In the current case the Data folder is located at this path in google drive (Use your own data path in your case)

/content/drive/Othercomputers/My MacBook Pro/Data/

We can sym link it to /content folder using the following command

In [ ]:
# sym linked the original data folder to new location at /content/Data
!ln -s "/content/drive/Othercomputers/My MacBook Pro/Data" "/content/Data"

Now we can access the data from this folder by simply giving the file path name after /Data

# Importing pandas library and data loading

In [ ]:
import pandas as pd

If you have saved the dataset in the previous tutorial in the file "Imdb_movies_saved.csv" file than you can access it from the following path

In [ ]:
# if you are working with this tutorial on local machine use the file path where the data is saved in your computer
movies = pd.read_csv("Data/IMDB_rotten_tomato_dataset/IMDB/Imdb_movies_saved.csv")
# We can use .head command to quickly observe the first 5 rows of the dataset
movies.head()

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (3) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

  imdb_title_id  ... reviews_from_critics
0     tt0000009  ...                  2.0
1     tt0000574  ...                  7.0
2     tt0001892  ...                  2.0
3     tt0002101  ...                  3.0
4     tt0002130  ...                 14.0

[5 rows x 22 columns]

# Filtering

## Filter column

We can filter data by a feature or column

For eg. We can filter and print data in 'language' column like below

In [ ]:
movies['language']

0                 None
1                 None
2                  NaN
3              English
4              Italian
             ...
85850           French
85851    German, Dutch
85852        Malayalam
85853          Turkish
85854          Catalan
Name: language, Length: 85855, dtype: object

## Filter rows based on column conditions

We can also filter rows in the data with "specific values (or value ranges) within specific features."

For eg. let us suppose we want to filter movies which are made in English

**Filter movies made in english**

First we create a mask dataframe using the comparison operator '=='. 

It compares each row value of 'language' columns with 'English'.

If 'English' is in the row then it is true otherwise false.

In [ ]:
# Creating a mask
mask = movies['language']=='English'
print(mask)

0        False
1        False
2        False
3         True
4        False
         ...
85850    False
85851    False
85852    False
85853    False
85854    False
Name: language, Length: 85855, dtype: bool

Comparing 'language' column with above mask we can observe that wherever we have value 'English' (it should be just 'English' and not combined with other language), then it is True otherwise False

In [ ]:
movies['language']

0                 None
1                 None
2                  NaN
3              English
4              Italian
             ...
85850           French
85851    German, Dutch
85852        Malayalam
85853          Turkish
85854          Catalan
Name: language, Length: 85855, dtype: object

Now we apply mask dataframe with movies.loc function to just select those rows where we have 'English' as the language

In [ ]:
# using mask inside .loc filters out True rows only from mask dataframe
movies.loc[mask]

      imdb_title_id  ... reviews_from_critics
3         tt0002101  ...                  3.0
5         tt0002199  ...                  5.0
9         tt0002461  ...                  1.0
17        tt0003167  ...                  NaN
19        tt0003471  ...                 11.0
...             ...  ...                  ...
85827     tt9883996  ...                  5.0
85830     tt9887580  ...                  5.0
85837     tt9894470  ...                 94.0
85838     tt9896916  ...                  3.0
85839     tt9898858  ...                 64.0

[35939 rows x 22 columns]

More generally we do not initialise mask first, we write mask and filter operation in one line only

In [ ]:
movies.loc[movies['language']=='English']

      imdb_title_id  ... reviews_from_critics
3         tt0002101  ...                  3.0
5         tt0002199  ...                  5.0
9         tt0002461  ...                  1.0
17        tt0003167  ...                  NaN
19        tt0003471  ...                 11.0
...             ...  ...                  ...
85827     tt9883996  ...                  5.0
85830     tt9887580  ...                  5.0
85837     tt9894470  ...                 94.0
85838     tt9896916  ...                  3.0
85839     tt9898858  ...                 64.0

[35939 rows x 22 columns]

But if you see all_lang, you will observe that many English movies are released in other languages as well.

In [ ]:
# access all the langauges in languages column
all_lang = movies['language'].unique()
all_lang[0:50]

array(['None', nan, 'English', 'Italian', 'German', 'Danish', 'French',
       'German, English', 'None, English', 'Hungarian', 'Russian',
       'English, German', 'Spanish', 'Dutch', 'Swedish',
       'Swedish, Danish', 'English, None', 'Japanese',
       'Latin, French, English', 'English, French',
       'None, English, French', 'None, French', 'English, Greek',
       'English, Yiddish', 'Sign Languages', 'English, Spanish',
       'English, Mandarin', 'Mandarin', 'None, Russian', 'Czech',
       'English, Spanish, Italian', 'English, Polynesian',
       'English, Cantonese, German', 'English, French, German, Latin',
       'English, Russian', 'German, English, French',
       'English, Italian, French', 'Russian, German, French, Yiddish',
       'English, German, French', 'English, Italian',
       'English, French, Spanish, Arabic, Italian',
       'English, Spanish, French', 'Vietnamese, French',
       'English, German, Italian', 'English, Mandarin, French',
       'French, Romanian', 'German, French', 'Hindi, Urdu',
       'English, Italian, Swedish', 'English, French, German'],
      dtype=object)

The above dataframe contains those movies which are released in English only and not other languages. 

what if we want all movies which are made in English (whether or not they have other language versions)

We need to create a new mask dataframe. In this mask dataframe for each row value in langauge column we are checking if the value contains the word 'English' or not.

For applying this contains function, we need to use .str after the column.

In [ ]:
mask_str = movies['language'].str.contains('English')
print(mask_str)

0        False
1        False
2          NaN
3         True
4        False
         ...
85850    False
85851    False
85852    False
85853    False
85854    False
Name: language, Length: 85855, dtype: object

If you observe the above dataframe you will see some of the values are NaN, these are those rows where no language value is mentioned.

If we apply the above mask operation for filtering out rows with 'English' language we will face an error

In [ ]:
# you will get an error here
movies.loc[movies['language'].str.contains('English')]

ValueError: ignored

Mask should always have True or False value, No NA/NaN values are allowed, so we need to discard rows with NA/NaN values.

They can be discarded using the below code as shown

In [ ]:
# using na argument inside contains function to drop na rows
movies.loc[movies['language'].str.contains('English',na=False)]

      imdb_title_id  ... reviews_from_critics
3         tt0002101  ...                  3.0
5         tt0002199  ...                  5.0
9         tt0002461  ...                  1.0
17        tt0003167  ...                  NaN
18        tt0003419  ...                 26.0
...             ...  ...                  ...
85837     tt9894470  ...                 94.0
85838     tt9896916  ...                  3.0
85839     tt9898858  ...                 64.0
85841     tt9899880  ...                 13.0
85846     tt9904802  ...                  6.0

[47446 rows x 22 columns]

Below we have broken down the steps that we have taken for above filtering. 

**Step-by-step explanation (from inner to outer):**<br>
* movies\['language'\] selects the language column of the data frame (technically, the object movies\['language'\] is of type pandas.Series)<br>
* movies\['language'\].str allows us to apply vectorized string methods (e.g., lower, contains) to the Series<br>
* movies\['language'\].str.contains('English') checks each element of the Series as to whether the element value has the string 'English' as a substring. The result is a Series of Booleans indicating True or False about the existence of a 'English' substring.<br>
* movies.loc\[movies\['language'\].str.contains('English')\]applies the Boolean 'mask' to the dataframe and returns a view containing appropriate records.<br>
* na = False removes NA / NaN values from consideration; otherwise a ValueError may be returned.<br>

If we just want to select the column 'original title in above filter we can do so as shown below

In [ ]:
movies.loc[movies['language'].str.contains('English',na=False),'original_title']

3                                                Cleopatra
5        From the Manger to the Cross; or, Jesus of Naz...
9                                              Richard III
17                                        Home, Sweet Home
18                                    Der Student von Prag
                               ...
85837                                                  VFW
85838                               The Pilgrim's Progress
85839                                      Coffee & Kareem
85841                                             Columbus
85846                                          Enemy Lines
Name: original_title, Length: 47446, dtype: object

### Filter rows based on multiple column conditions

**Filter movies made in english with runtime more than 120 min**<br>
We can use & operator to check if both conditions are True then only we filter out those rows

In [ ]:
movies.loc[(movies['language'].str.contains('English',na=False)) & (movies['duration']>120)]

      imdb_title_id  ... reviews_from_critics
36        tt0004465  ...                  8.0
76        tt0006864  ...                 77.0
91        tt0007801  ...                  3.0
95        tt0008150  ...                  8.0
260       tt0012532  ...                 24.0
...             ...  ...                  ...
85706     tt9738784  ...                 15.0
85735     tt9777644  ...                217.0
85747     tt9784456  ...                 46.0
85769     tt9811598  ...                  1.0
85806     tt9850264  ...                  4.0

[3473 rows x 22 columns]