<a href="https://colab.research.google.com/drive/12FYMkzt9BUiFEpq6WjbtXaCjPTtlDriX?usp=sharing">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

This tutorial needs data so if you working on colab follow the below data setup instruction

# Data Setup Instructions

These are the instructions for mounting the data from google drive to colab and accessing it in the colab.

STEP 1 - After opening the tutorial in  your colab, go to folder button and click on mount google drive

STEP 2 - drive folder will be mounted in the current directory of /content, you can access it as below

In [ ]:
# print current directory
%pwd

'/content'

In [ ]:
%ls

drive/  sample_data/

STEP 3 - Find your data folder where you saved the data and sym link it to /content folder so as to simplify data access

In the current case the Data folder is located at this path in google drive (Use your own data path in your case)

/content/drive/Othercomputers/My MacBook Pro/Data/

We can sym link it to /content folder using the following command

In [ ]:
# sym linked the original data folder to new location at /content/Data
!ln -s "/content/drive/Othercomputers/My MacBook Pro/Data" "/content/Data"

Now we can access the data from this folder by simply giving the file path name after /Data

# Importing pandas library and data loading

In [ ]:
import pandas as pd

If you have saved the dataset in the previous tutorial in the file "Imdb_movies_saved.csv" file than you can access it from the following path

In [ ]:
# if you are working with this tutorial on local machine use the file path where the data is saved in your computer
movies = pd.read_csv("Data/IMDB_rotten_tomato_dataset/IMDB/Imdb_movies_saved.csv")
# We can use .head command to quickly observe the first 5 rows of the dataset
movies.head()

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (3) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

  imdb_title_id  ... reviews_from_critics
0     tt0000009  ...                  2.0
1     tt0000574  ...                  7.0
2     tt0001892  ...                  2.0
3     tt0002101  ...                  3.0
4     tt0002130  ...                 14.0

[5 rows x 22 columns]

# Pandas function for basic data exploration

These functions are helpful in exploring a dataset as soon as we load the dataset without applying any complex operations or methods. So it essential that we remember these functions

**Knowing the number of rows and columns in data**

In [ ]:
movies.shape

(85855, 22)

**Knowing column names and some information about columns**

In [ ]:
movies.columns

Index(['imdb_title_id', 'title', 'original_title', 'year', 'date_published',
       'genre', 'duration', 'country', 'language', 'director', 'writer',
       'production_company', 'actors', 'description', 'avg_vote', 'votes',
       'budget', 'usa_gross_income', 'worlwide_gross_income', 'metascore',
       'reviews_from_users', 'reviews_from_critics'],
      dtype='object')

In [ ]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85855 entries, 0 to 85854
Data columns (total 22 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   imdb_title_id          85855 non-null  object
 1   title                  85855 non-null  object
 2   original_title         85855 non-null  object
 3   year                   85855 non-null  object
 4   date_published         85855 non-null  object
 5   genre                  85855 non-null  object
 6   duration               85855 non-null  int64
 7   country                85791 non-null  object
 8   language               85022 non-null  object
 9   director               85768 non-null  object
 10  writer                 84283 non-null  object
 11  production_company     81400 non-null  object
 12  actors                 85786 non-null  object
 13  description            83740 non-null  object
 14  avg_vote               85855 non-null  float64
 15  votes                  85855 non-null  int64
 16  budget                 23710 non-null  object
 17  usa_gross_income       15326 non-null  object
 18  worlwide_gross_income  31016 non-null  object
 19  metascore              13305 non-null  float64
 20  reviews_from_users     78258 non-null  float64
 21  reviews_from_critics   74058 non-null  float64
dtypes: float64(4), int64(2), object(16)
memory usage: 14.4+ MB

**Numerical columns**

In [ ]:
# access one of the numerical column
movies['duration'].head()

0     45
1     70
2     53
3    100
4     68
Name: duration, dtype: int64

In [ ]:
# get statistical information about numerical columns
movies.describe()

           duration      avg_vote  ...  reviews_from_users  reviews_from_critics
count  85855.000000  85855.000000  ...        78258.000000          74058.000000
mean     100.351418      5.898656  ...           46.040826             27.479989
std       22.553848      1.234987  ...          178.511411             58.339158
min       41.000000      1.000000  ...            1.000000              1.000000
25%       88.000000      5.200000  ...            4.000000              3.000000
50%       96.000000      6.100000  ...            9.000000              8.000000
75%      108.000000      6.800000  ...           27.000000             23.000000
max      808.000000      9.900000  ...        10472.000000            999.000000

[8 rows x 6 columns]

**Categorical or Text based columns**

In [ ]:
# access year column - year column is perceived as text column rather than number columns
movies['year']

0        1894
1        1906
2        1911
3        1912
4        1911
         ...
85850    2020
85851    2020
85852    2019
85853    2019
85854    2019
Name: year, Length: 85855, dtype: object

In [ ]:
# access language column
movies['language']

0                 None
1                 None
2                  NaN
3              English
4              Italian
             ...
85850           French
85851    German, Dutch
85852        Malayalam
85853          Turkish
85854          Catalan
Name: language, Length: 85855, dtype: object

In [ ]:
# access description  column
movies['description']

0        The adventures of a female reporter in the 1890s.
1        True story of notorious Australian outlaw Ned ...
2        Two men of high rank are both wooing the beaut...
3        The fabled queen of Egypt's affair with Roman ...
4        Loosely adapted from Dante's Divine Comedy and...
                               ...
85850    A psychiatric hospital patient pretends to be ...
85851    A middle-aged veterinary surgeon believes his ...
85852                                                  NaN
85853                                                  NaN
85854    Pep, a 13-year-old boy, is in love with a girl...
Name: description, Length: 85855, dtype: object

In [ ]:
# access all the langauges in languages column
all_lang = movies['language'].unique()
all_lang

array(['None', nan, 'English', ..., 'Persian, Urdu',
       'English, Swiss German, German',
       'English, Polish, Russian, German'], dtype=object)

In [ ]:
len(all_lang)

4378

In [ ]:
all_lang[0:50]

array(['None', nan, 'English', 'Italian', 'German', 'Danish', 'French',
       'German, English', 'None, English', 'Hungarian', 'Russian',
       'English, German', 'Spanish', 'Dutch', 'Swedish',
       'Swedish, Danish', 'English, None', 'Japanese',
       'Latin, French, English', 'English, French',
       'None, English, French', 'None, French', 'English, Greek',
       'English, Yiddish', 'Sign Languages', 'English, Spanish',
       'English, Mandarin', 'Mandarin', 'None, Russian', 'Czech',
       'English, Spanish, Italian', 'English, Polynesian',
       'English, Cantonese, German', 'English, French, German, Latin',
       'English, Russian', 'German, English, French',
       'English, Italian, French', 'Russian, German, French, Yiddish',
       'English, German, French', 'English, Italian',
       'English, French, Spanish, Arabic, Italian',
       'English, Spanish, French', 'Vietnamese, French',
       'English, German, Italian', 'English, Mandarin, French',
       'French, Romanian', 'German, French', 'Hindi, Urdu',
       'English, Italian, Swedish', 'English, French, German'],
      dtype=object)