<a href="https://colab.research.google.com/github/OneLearn-github/Introductory_Data_Analytics_Course/blob/main/basic_python_revision/Coding_Assignment_stringmethods_listcomprehension.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

**No1**<br>
Given a string, we need to replace all commas with dots

In [ ]:
#example string
a = '14,645,34,94'
# write your program here

**No2**<br>
Given the list : a = [1, 4, 9, 16, 25, 36, 49, 64, 81, 100]. 

Write one line of Python code that takes this list a and makes a new list that has only the odd elements of this list in it.

**No 3**<br>
Ask the user for a string and print out whether this string is a palindrome or not. (A palindrome is a string that reads the same forwards and backwards.)

**No 4**<br>
Count the number of elements in a list within a specified range.<br>
Given list is - list1 = [10,20,30,40,40,40,70,80,99]<br>
and range is - 40, 85