<a href="https://colab.research.google.com/github/OneLearn-github/Introductory_Data_Analytics_Course/blob/main/basic_python_revision/Solution_coding_ass_func_lambda.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

No 1 . Write a function that takes two arguments (feet and inches) and returns height in meters .

No 2 . Write a function in python to display the elements of list 
* once if it is a number For eg. if element is 34 just print 34
* if it is not a number print all the characters in the string as a list. For eg. if element is "STAR" print ['S','T','A','R']

Example: <br>
Sample Input : l1 = [34,55,"STAR", "ONE", 2, "TWO"] <br>
Sample Output: <br>
34 <br>
55 <br>
['S','T', 'A', 'R'] <br>
['O','N', 'E'] <br>
2 <br>
['T', 'W', 'O']

In [2]:
def list_print_func(inp_list):
  for inp_list_elem in inp_list:
    inp_list_elem = str(inp_list_elem)
    if inp_list_elem.isdigit():
      print(inp_list_elem)
    else:
      new_list = []
      for char in inp_list_elem:
        new_list.append(char)
      print(new_list)

list_print_func([1,2,'STAR',214,'234','1SQ'])

1
2
['S', 'T', 'A', 'R']
214
234
['1', 'S', 'Q']

No 3 . Write a Python program to create a lambda function that adds 10 to a given number passed in as an argument, also create a lambda function that multiplies argument x with argument y and print the result

In [ ]:
r = lambda a : a + 10
print(r(10))
r = lambda a, b : a * b
print(r(12, 4))

20
48

No 4 . Write a Python program to find whether a given string starts with a given character using Lambda.

In [ ]:
starts_with = lambda x: True if x.startswith('P') else False
print(starts_with('Python'))
starts_with = lambda x: True if x.startswith('O') else False
print(starts_with('OneLearn'))

True
True